[dependencies]
"php/php-32" = "=8.3.2101-rc.1"

[fs]
"/app" = "app"
"/config" = "config"

[[command]]
name = "run"
module = "php/php-32:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]
env = ["PHPRC=/config/"]
